package com.akinci.androidtemplate.core.application

import com.akinci.androidtemplate.BuildConfig
import javax.inject.Inject

/**
 *  AppConfig is a wrapper class for BuildConfig fields.
 *
 *  This class provides:
 *  - Encapsulation for autogenerated BuildConfig fields.
 *  - Removes implementation difficulties of unit testing classes.
 *  - BuildConfig can be easily mocked via AppConfig class.
 * **/
class AppConfig @Inject constructor() {
    fun isDebugMode() = BuildConfig.DEBUG
}
